import { expect, test } from '@playwright/test'

test('完整出牌记录按固定座位展示，新增当前墩保留所有旧墩', async ({ page }) => {
  await page.goto('/tests/browser/history.html')
  const history = page.getByRole('region', { name: '公开出牌记录', exact: true })
  await expect(history.getByRole('columnheader')).toHaveText(['墩', '东', '南', '西', '北'])
  await expect(history.getByRole('row')).toHaveCount(11)
  await expect(history.getByRole('row').nth(1)).toContainText('♣2')
  await expect(history.getByRole('row').nth(1)).toContainText('首引')
  await expect(history.getByRole('row').nth(1)).toContainText('赢墩')
  await page.getByRole('button', { name: '收到新出牌' }).click()
  await expect(history.getByRole('row')).toHaveCount(12)
  await expect(history.getByRole('row').last()).toContainText('♠A')
  await page.getByRole('button', { name: '完成十三墩' }).click()
  await expect(history.getByRole('row')).toHaveCount(14)
  await expect(history.getByRole('row').last().getByRole('rowheader')).toHaveText('13')
  await expect(history.getByText('当前', { exact: true })).toHaveCount(0)
})

test('翻看旧墩时新出牌不抢位置，回到最新后自动跟随，下一副清空记录', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/browser/history.html')
  const list = page.getByRole('region', { name: '出牌记录列表' })
  await list.hover()
  await page.mouse.wheel(0, -1500)
  await expect.poll(() => list.evaluate(el => el.scrollTop)).toBe(0)
  await page.getByRole('button', { name: '收到新出牌' }).click()
  await expect(page.getByText('有新出牌', { exact: true })).toBeVisible()
  await expect.poll(() => list.evaluate(el => el.scrollTop)).toBe(0)
  await page.getByRole('button', { name: '回到最新' }).click()
  await expect.poll(() => list.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2)
  await page.getByRole('button', { name: '收到新出牌' }).click()
  await expect.poll(() => list.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2)
  await page.getByRole('button', { name: '下一副', exact: true }).click()
  await expect(list.getByRole('row')).toHaveCount(2)
  await expect(list).toContainText('等待首引')
  await expect(page.getByText('有新出牌', { exact: true })).toHaveCount(0)
})

test('手机记录可展开收起，独立滚动且查看手牌时常驻；电脑记录在牌桌侧边', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tests/browser/history.html')
  const history = page.getByRole('region', { name: '公开出牌记录', exact: true })
  const list = page.getByRole('region', { name: '出牌记录列表' })
  const compactHeight = (await list.boundingBox())!.height
  await page.getByRole('button', { name: '展开记录' }).click()
  await expect.poll(async () => (await list.boundingBox())!.height).toBeGreaterThan(compactHeight)
  await page.getByRole('button', { name: '收起记录' }).click()
  await expect.poll(async () => (await list.boundingBox())!.height).toBe(compactHeight)
  const pageTop = await page.evaluate(() => window.scrollY)
  await list.hover()
  await page.mouse.wheel(0, -2000)
  await expect.poll(() => list.evaluate(el => el.scrollTop)).toBe(0)
  expect(await page.evaluate(() => window.scrollY)).toBe(pageTop)
  await page.getByRole('button', { name: '回到最新' }).click()
  await page.getByRole('button', { name: '黑桃 A', exact: true }).scrollIntoViewIfNeeded()
  const rect = (await history.boundingBox())!
  expect(rect.y).toBeGreaterThanOrEqual(0)
  expect(rect.y + rect.height).toBeLessThan(844)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/tests/browser/history.html')
  const table = (await page.getByRole('region', { name: '四方座位' }).boundingBox())!
  const desktopHistory = (await history.boundingBox())!
  expect(desktopHistory.x).toBeGreaterThanOrEqual(table.x + table.width)
  await page.screenshot({ path: testInfo.outputPath('desktop.png'), fullPage: true })
})
